$('.owl-carousel').owlCarousel({
    loop:true,
    margin:0,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        720:{
            items:2,
            nav:false
        },
        1080:{
            items:3,
        },
        1300:{
            items:4,
            nav:true,
            loop:false
        }
    }
})